# Generated by Django 6.1.1 on 2026-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_price_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'order number counter',
                'verbose_name_plural': 'order number counters',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveBigIntegerField(default=0, unique=True, verbose_name='order number'),
            preserve_default=False,
        ),
    ]
