# Generated by Django 6.1.1 on 2026-09-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_default_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_address',
            field=models.TextField(blank=True, default='', verbose_name='default address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='phone'),
        ),
    ]
